server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive
    allow-circular-references: true
  config:
    import: optional:configserver:http://localhost:8085
  cloud:
    gateway:
      routes:
        - id: IDENTITY-SERVICE
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
logging:
  level:
    org.springframework.web: DEBUG
