server:
  port: 9018

spring:
  application:
    name: NOTIFICATION-SERVICE
  config:
    import: optional:configserver:http://localhost:8085

# Kafka server url
# Connection to server kafka
  kafka:
    bootstrap-servers: localhost:9092
    # Convert Object To Byte
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # 0 no wait for kafka response
      # 1 leader write success, no wait for follower
      # -1 wait for all leader, and replication
      acks: -1
      retries: 1
      properties:
        requests.timeout.ms: 1
        #prevent duplicate send
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
